name: ci
concurrency: ${{ github.workflow }}-${{ github.ref }}
on:
  push:
  pull_request:
jobs:
  typecheck:
    name: 🧪 typecheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: oviirup/actions/bun@v1
      - run: bun run typecheck
  lint:
    name: 🧪 lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: oviirup/actions/bun@v1
      - run: bun run lint
  test:
    name: 🧪 test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: oviirup/actions/bun@v1
      - run: bun run test
