name: publish
concurrency: ${{ github.workflow }}-${{ github.ref }}
on:
  workflow_run:
    workflows: [ci]
    types: [completed]
    branches: [main]
jobs:
  # select changeset mode if ci run successfully
  mode:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      mode: ${{ steps.changesets-mode.outputs.mode }}
      publish-plan-artifact-id: ${{ steps.changesets-mode.outputs.publish-plan-artifact-id }}
    steps:
      - name: 🔷 Checkout
        uses: actions/checkout@v7
      - name: 🟢 Setup bun
        uses: oviirup/actions/bun@v1
      - name: 🔧 Select changesets mode
        id: changesets-mode
        uses: changesets/action/select-mode@v2
  # update the version of the packages
  version:
    if: needs.mode.outputs.mode == 'version'
    needs: mode
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: 🔷 Checkout
        uses: actions/checkout@v7
      - name: 🟢 Setup bun
        uses: oviirup/actions/bun@v1
      - name: 🏷️ Update version
        id: version
        uses: changesets/action/version@v2
        with:
          script: bun changeset version
          commit-message: "✅ chore: update version"
          pr-title: "✅ chore: update version"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # pack the package artifacts
  pack:
    if: needs.mode.outputs.mode == 'publish'
    needs: mode
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      pack-dir-artifact-id: ${{ steps.pack.outputs.pack-dir-artifact-id }}
    steps:
      - name: 🔷 Checkout
        uses: actions/checkout@v7
      - name: 🟢 Setup bun
        uses: oviirup/actions/bun@v1
      - name: 📦 Build
        run: bun run build
      - name: 📦 Pack artifacts
        id: pack
        uses: changesets/action/pack@v2
        with:
          publish-plan-artifact-id: ${{ needs.mode.outputs.publish-plan-artifact-id }}
  # publish the package
  publish:
    needs: pack
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 🔷 Checkout
        uses: actions/checkout@v7
      - name: 🟢 Setup bun
        uses: oviirup/actions/bun@v1
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org/
      - name: 📦 Build
        run: bun run build
      - name: ⚙️ Publish packages
        id: publish
        uses: changesets/action/publish@v2
        with:
          pack-dir-artifact-id: ${{ needs.pack.outputs.pack-dir-artifact-id }}
          create-github-releases: true
          push-git-tags: true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}